# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Guards

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f backend/requirements.dev.txt ]; then pip install -r backend/requirements.dev.txt; fi
          if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi
      - name: autoflake
        run: |
          autoflake \
            --in-place \
            --expand-star-imports \
            --remove-duplicate-keys \
            --remove-unused-variables \
            --remove-all-unused-imports \
            --recursive \
            .
      - name: black
        run: |
          black . --line-length=120
      - name: isort
        run: |
          isort . --profile black --filter-files
      - name: pytest
        run: |
          pytest -sv
